import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, it } from "node:test";

import {
  NODE_IMAGE,
  collectApplicationContainerViolations,
  validateRepositoryApplicationContainers,
} from "./check-app-containers.mjs";

const root = process.cwd();
const valid = {
  databaseMigrationSource: readFileSync(
    path.join(root, "packages/db/scripts/strict-migrate.mjs"),
    "utf8",
  ),
  databasePackageSource: readFileSync(
    path.join(root, "packages/db/package.json"),
    "utf8",
  ),
  composeSource: readFileSync(path.join(root, "compose.yaml"), "utf8"),
  databaseSetupSource: readFileSync(
    path.join(root, "packages/db/scripts/prepare-local-app-profile.mjs"),
    "utf8",
  ),
  dockerfiles: Object.fromEntries(
    ["api", "jobs", "web"].map((app) => [
      app,
      readFileSync(path.join(root, "apps", app, "Dockerfile"), "utf8"),
    ]),
  ),
  dockerignoreSource: readFileSync(path.join(root, ".dockerignore"), "utf8"),
  jobsContainerSource: readFileSync(
    path.join(root, "apps/jobs/src/container.ts"),
    "utf8",
  ),
  jobsRunnerSource: readFileSync(
    path.join(root, "apps/jobs/src/development-runner.ts"),
    "utf8",
  ),
  lifecycleSource: readFileSync(
    path.join(root, "scripts/local-apps.sh"),
    "utf8",
  ),
};

describe("application container policy", () => {
  it("accepts the checked-in images, profile, and lifecycle", () => {
    assert.deepEqual(validateRepositoryApplicationContainers(root), []);
  });

  it("rejects toolchain drift and cross-application packaging", () => {
    const dockerfiles = {
      ...valid.dockerfiles,
      api: valid.dockerfiles.api
        .replace(NODE_IMAGE, "node:24-bookworm-slim")
        .replace("pnpm@10.34.5", "pnpm@latest")
        .replace("--filter @reflo/api", "--filter @reflo/web"),
    };
    const errors = collectApplicationContainerViolations({
      ...valid,
      dockerfiles,
    });

    assert.ok(
      errors.includes(
        "apps/api/Dockerfile must use only the exact pinned Node image in both stages",
      ),
    );
    assert.ok(errors.includes("missing apps/api exact pnpm activation"));
    assert.ok(errors.includes("missing apps/api independent workspace build"));
    assert.ok(
      errors.includes(
        "apps/api/Dockerfile must not package the web application",
      ),
    );
  });

  it("rejects secret build inputs and exposed or unhealthy services", () => {
    const dockerfiles = {
      ...valid.dockerfiles,
      jobs: `${valid.dockerfiles.jobs}\nARG PROVIDER_TOKEN\n`,
    };
    const composeSource = valid.composeSource
      .replace(
        '"127.0.0.1:${REFLO_LOCAL_API_PORT:-53001}:3001"',
        '"0.0.0.0:53001:3001"',
      )
      .replace(/(  api:\n[\s\S]*?)    healthcheck:/, "$1    readiness:");
    const errors = collectApplicationContainerViolations({
      ...valid,
      composeSource,
      dockerfiles,
    });

    assert.ok(
      errors.includes(
        "apps/jobs/Dockerfile must not declare credential inputs",
      ),
    );
    assert.ok(errors.includes("missing api loopback-only host port"));
    assert.ok(errors.includes("missing api Compose health check"));
  });

  it("rejects broad or user-directed lifecycle cleanup", () => {
    const lifecycleSource = `${valid.lifecycleSource}\ndocker system prune\nrun_compose "$@"\n`;
    const errors = collectApplicationContainerViolations({
      ...valid,
      lifecycleSource,
    });

    assert.ok(
      errors.includes(
        "application lifecycle must not accept arbitrary Compose arguments or remove unrelated Docker resources",
      ),
    );
  });

  it("rejects an owner-credential API and readiness-only jobs container", () => {
    const composeSource = valid.composeSource.replace(
      "postgresql://reflo_api:${REFLO_LOCAL_API_RDS_PASSWORD:?generated by scripts/local-stack.sh}@rds",
      "postgresql://reflo:${REFLO_LOCAL_RDS_PASSWORD:?generated by scripts/local-stack.sh}@rds",
    );
    const jobsContainerSource = valid.jobsContainerSource.replaceAll(
      "runDevelopmentJob",
      "ignoredDevelopmentJob",
    );
    const errors = collectApplicationContainerViolations({
      ...valid,
      composeSource,
      jobsContainerSource,
    });

    assert.ok(errors.includes("missing DML-only API database credential"));
    assert.ok(
      errors.includes(
        "API runtime must not receive the database owner credential",
      ),
    );
    assert.ok(
      errors.includes("missing jobs container bounded runner composition"),
    );
  });

  it("requires a default-deny context and runtime artifact scan", () => {
    const dockerfiles = {
      ...valid.dockerfiles,
      web: valid.dockerfiles.web.replace(
        "find /workspace/apps/web/out",
        "find /tmp",
      ),
    };
    const dockerignoreSource = valid.dockerignoreSource.replace("**", ".git");
    const errors = collectApplicationContainerViolations({
      ...valid,
      dockerfiles,
      dockerignoreSource,
    });

    assert.ok(
      errors.includes(".dockerignore must default-deny the build context"),
    );
    assert.ok(errors.includes("missing apps/web runtime artifact secret scan"));
  });

  it("rejects a setup command whose relative path silently bypasses execution", () => {
    const composeSource = valid.composeSource.replace(
      "/opt/reflo/api/node_modules/@reflo/db/scripts/prepare-local-app-profile.mjs",
      "node_modules/@reflo/db/scripts/prepare-local-app-profile.mjs",
    );
    const errors = collectApplicationContainerViolations({
      ...valid,
      composeSource,
    });

    assert.ok(
      errors.includes("missing repository-owned application database setup"),
    );
  });

  it("rejects migration execution through a deployment-fragile bin shim", () => {
    const databaseMigrationSource = valid.databaseMigrationSource
      .replaceAll("resolveDbmateCli()", '"dbmate"')
      .replaceAll("process.execPath", '"dbmate"');
    const errors = collectApplicationContainerViolations({
      ...valid,
      databaseMigrationSource,
    });

    assert.ok(
      errors.includes(
        "missing packaged database migration executable resolution",
      ),
    );
    assert.ok(
      errors.includes("missing Node-invoked database migration executable"),
    );
  });

  it("requires the local setup SQL in the deployed database package", () => {
    const databasePackageSource = valid.databasePackageSource.replace(
      '    "sql"',
      '    "missing-sql"',
    );
    const errors = collectApplicationContainerViolations({
      ...valid,
      databasePackageSource,
    });

    assert.ok(errors.includes("missing packaged local database setup SQL"));
  });
});
