#!/usr/bin/env node

import { createHash } from "node:crypto";
import { execFile, spawn } from "node:child_process";
import { constants as fsConstants } from "node:fs";
import {
  access,
  chmod,
  copyFile,
  cp,
  mkdtemp,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const generatedRoot = path.join(repositoryRoot, ".reflo", "local-workers");
const statePath = path.join(generatedRoot, "state.json");
const profileEnvironmentPath = path.join(generatedRoot, "profile.env");
const contractPath = path.join(
  repositoryRoot,
  "scripts",
  "local-workers-manifest.json",
);
const audioWorkerPath = path.join(
  repositoryRoot,
  "packages",
  "audio",
  "piper-worker",
  "worker.py",
);
const sha256Pattern = /^[a-f0-9]{64}$/;
const digestPattern = /^sha256:[a-f0-9]{64}$/;
const maximumCommandOutputBytes = 1024 * 1024;
const clamavAdmissionProfile = "upstream-clamav-cloud-demo-v1";
const clamavManifestContract = "upstream-clamav-snapshot-manifest-v1";

export class LocalWorkerError extends Error {
  constructor(state, component, action) {
    super(`${component}: ${action}`);
    this.name = "LocalWorkerError";
    this.state = state;
    this.component = component;
    this.action = action;
  }
}

export function isSupportedPodmanVersion(output, versions) {
  const match = output
    .trim()
    .match(/^podman version ([0-9]+\.[0-9]+\.[0-9]+)$/i);
  return match !== null && versions.includes(match[1]);
}

export function parsePodmanVersionReport(output) {
  let report;
  try {
    report = JSON.parse(output);
  } catch {
    return undefined;
  }
  const clientVersion = report.Client?.Version;
  const serverVersion = report.Server?.Version;
  if (
    typeof clientVersion !== "string" ||
    typeof serverVersion !== "string" ||
    !/^[0-9]+\.[0-9]+\.[0-9]+$/.test(clientVersion) ||
    !/^[0-9]+\.[0-9]+\.[0-9]+$/.test(serverVersion)
  ) {
    return undefined;
  }
  return { clientVersion, serverVersion };
}

export function podmanVersionReportIsSupported(report, versions) {
  return (
    report !== undefined &&
    report.clientVersion === report.serverVersion &&
    versions.includes(report.clientVersion)
  );
}

export function hostPlatformKey(
  platform = process.platform,
  arch = process.arch,
) {
  return `${platform}/${arch}`;
}

export function unexpectedClamavDirectoryEntries(
  entries,
  selectedDatabases,
  allowedMetadataFiles,
) {
  const allowedEntries = new Set([
    ...selectedDatabases,
    ...allowedMetadataFiles,
  ]);
  return entries
    .filter((entry) => !entry.isFile() || !allowedEntries.has(entry.name))
    .map((entry) => entry.name)
    .sort();
}

export function piperStatePathsMatch(state, piperDirectory, voiceContract) {
  const expectedPaths = {
    configPath: path.join(
      piperDirectory,
      path.basename(voiceContract.configPath),
    ),
    modelPath: path.join(
      piperDirectory,
      path.basename(voiceContract.modelPath),
    ),
    preflightWavPath: path.join(piperDirectory, "preflight.wav"),
    pythonExecutable: path.join(piperDirectory, "venv", "bin", "python"),
  };
  return Object.entries(expectedPaths).every(
    ([key, expected]) =>
      typeof state?.[key] === "string" &&
      path.resolve(state[key]) === path.resolve(expected),
  );
}

export function renderProfileEnvironment(state) {
  const entries = {
    REFLO_ENV: "dev",
    REFLO_DEMO_UPLOAD_MALWARE_SCANNER_MODE: clamavAdmissionProfile,
    REFLO_LOCAL_CLAMAV_ADMISSION_DATABASE_DIR: state.clamavAdmission.directory,
    REFLO_LOCAL_CLAMAV_DATABASE_DIR: state.clamav.directory,
    REFLO_LOCAL_CLAMAV_MANIFEST_PATH: state.clamavAdmission.manifestPath,
    REFLO_LOCAL_CLAMAV_SCANNER_IMAGE: state.clamavAdmission.scannerImage,
    REFLO_LOCAL_CLAMAV_SNAPSHOT_ID: state.clamavAdmission.snapshotId,
    REFLO_LOCAL_INGESTION_IMAGE: state.ingestion.imageReference,
    REFLO_LOCAL_INGESTION_IMAGE_DIGEST: state.ingestion.imageDigest,
    REFLO_LOCAL_PIPER_ARTIFACT_REVISION: state.piper.artifactRevision,
    REFLO_LOCAL_PIPER_CONFIG_PATH: state.piper.configPath,
    REFLO_LOCAL_PIPER_CONFIG_SHA256: state.piper.configSha256,
    REFLO_LOCAL_PIPER_MODEL_PATH: state.piper.modelPath,
    REFLO_LOCAL_PIPER_MODEL_SHA256: state.piper.modelSha256,
    REFLO_LOCAL_PIPER_PYTHON: state.piper.pythonExecutable,
    REFLO_LOCAL_PIPER_VOICE_ARTIFACT_VERSION: state.piper.voiceArtifactVersion,
    REFLO_LOCAL_SMOKE_VIDEO: "false",
    REFLO_LOCAL_TESSDATA_DIR: state.tessdata.directory,
  };
  return (
    "# Generated by scripts/local-workers.mjs. Contains no credentials.\n" +
    Object.entries(entries)
      .map(([key, value]) => `${key}=${shellQuote(value)}`)
      .join("\n") +
    "\n"
  );
}

export function validateLocalWorkersContract(
  contract,
  ingestionManifest,
  piperManifest,
  containerfile,
) {
  const errors = [];
  if (
    contract.contractVersion !== "reflo-local-workers-v2" ||
    contract.stateVersion !== "reflo-local-workers-state-v2" ||
    contract.profile !== "development-only"
  ) {
    errors.push("invalid local-worker contract identity");
  }
  if (
    JSON.stringify(contract.supportedPodmanVersions) !==
    JSON.stringify(["5.8.3", "6.0.1"])
  ) {
    errors.push("Podman compatibility must be exactly 5.8.3 or 6.0.1");
  }
  if (
    contract.ingestion.imageReference !== "reflo-ingestion-worker:local" ||
    contract.ingestion.platform !== "linux/amd64" ||
    contract.ingestion.profile !== ingestionManifest.profile
  ) {
    errors.push("invalid development ingestion image contract");
  }
  if (
    contract.clamav.version !== "1.4.5" ||
    contract.clamav.version !==
      ingestionManifest.components.scanner.replace("clamav-", "") ||
    !contract.clamav.updaterImage.endsWith(
      `@${contract.clamav.updaterImageDigest}`,
    ) ||
    !digestPattern.test(contract.clamav.updaterImageDigest) ||
    contract.clamav.maxAgeHours !== 24 ||
    JSON.stringify(contract.clamav.allowedMetadataFiles) !==
      JSON.stringify(["freshclam.dat"])
  ) {
    errors.push("invalid development ClamAV contract");
  }
  if (
    !containerfile.includes(contract.tessdata.url) ||
    !containerfile.includes(contract.tessdata.sha256) ||
    !sha256Pattern.test(contract.tessdata.sha256)
  ) {
    errors.push("tessdata does not match the ingestion Containerfile");
  }
  if (contract.piper.pythonVersion !== piperManifest.baseImage.pythonVersion) {
    errors.push("Piper Python version does not match the checked-in manifest");
  }
  if (
    contract.piper.version !== piperManifest.piper.version ||
    contract.piper.voice.profileId !== piperManifest.voice.profileId ||
    contract.piper.voice.voiceId !== piperManifest.voice.voiceId ||
    contract.piper.voice.revision !== piperManifest.voice.revision ||
    contract.piper.voice.modelPath !== piperManifest.voice.modelPath ||
    contract.piper.voice.modelSha256 !== piperManifest.voice.modelSha256 ||
    contract.piper.voice.configPath !== piperManifest.voice.configPath ||
    contract.piper.voice.configSha256 !== piperManifest.voice.configSha256
  ) {
    errors.push("Piper voice inputs do not match the checked-in manifest");
  }
  const runtimeKeys = new Set();
  for (const runtime of contract.piper.runtimes ?? []) {
    if (
      runtimeKeys.has(runtime.platform) ||
      !/^(?:darwin|linux)\/(?:arm64|x64)$/.test(runtime.platform) ||
      !sha256Pattern.test(runtime.piperWheelSha256) ||
      !sha256Pattern.test(runtime.onnxRuntimeWheelSha256) ||
      !runtime.piperWheel.includes(`piper_tts-${contract.piper.version}-`) ||
      !runtime.onnxRuntimeWheel.includes(
        `onnxruntime-${runtime.onnxRuntimeVersion}-`,
      )
    ) {
      errors.push("invalid Piper development runtime pin");
      break;
    }
    runtimeKeys.add(runtime.platform);
  }
  if (runtimeKeys.size !== 4) {
    errors.push("Piper development runtime matrix is incomplete");
  }
  return errors;
}

async function loadContracts() {
  const [contract, ingestionManifest, piperManifest, containerfile] =
    await Promise.all([
      readJson(contractPath),
      readJson(
        path.join(repositoryRoot, "packages/ingestion/worker/manifest.json"),
      ),
      readJson(
        path.join(repositoryRoot, "packages/audio/piper-worker/manifest.json"),
      ),
      readFile(
        path.join(repositoryRoot, "packages/ingestion/worker/Containerfile"),
        "utf8",
      ),
    ]);
  const errors = validateLocalWorkersContract(
    contract,
    ingestionManifest,
    piperManifest,
    containerfile,
  );
  if (errors.length > 0) {
    throw new LocalWorkerError("INVALID", "contract", errors.join("; "));
  }
  return { contract, ingestionManifest };
}

async function prepare() {
  assertGeneratedRoot();
  const { contract, ingestionManifest } = await loadContracts();
  const runtime = selectPiperRuntime(contract);
  await ensureDirectory(generatedRoot);

  console.info("Preparing optional Reflo development workers");
  const podman = await verifyPodmanHost(contract);
  const ingestion = await runPreparationStep(
    "ingestion-worker",
    "failed to build or verify the local ingestion image",
    () => prepareIngestion(contract, ingestionManifest, podman),
  );
  const tessdata = await runPreparationStep(
    "tessdata",
    "failed to prepare checksum-pinned English tessdata",
    () => prepareTessdata(contract),
  );
  const piper = await runPreparationStep(
    "piper",
    "failed to prepare the pinned Piper development environment",
    () => preparePiper(contract, runtime),
  );
  const clamav = await runPreparationStep(
    "clamav",
    "failed to refresh and verify the ClamAV development snapshot",
    () => prepareClamav(contract),
  );
  const clamavAdmission = await runPreparationStep(
    "clamav-admission",
    "publish and verify the upstream-signed ClamAV admission snapshot",
    () => prepareClamavAdmission(contract, clamav),
  );
  const state = {
    contractVersion: contract.stateVersion,
    preparedAt: new Date().toISOString(),
    profile: contract.profile,
    hostPlatform: hostPlatformKey(),
    podmanClientVersion: podman.clientVersion,
    podmanServerVersion: podman.serverVersion,
    ingestion,
    clamav,
    clamavAdmission,
    tessdata,
    piper,
  };
  await writePrivateJson(statePath, state);
  await writePrivateFile(
    profileEnvironmentPath,
    renderProfileEnvironment(state),
  );

  const readiness = await collectReadiness(contract, ingestionManifest);
  printReadiness(readiness);
  if (!readiness.every((item) => item.state === "AVAILABLE")) {
    throw new LocalWorkerError(
      "INVALID",
      "local-workers",
      "preparation completed but readiness verification failed",
    );
  }
  console.info(`Profile environment: ${profileEnvironmentPath}`);
}

async function status() {
  const { contract, ingestionManifest } = await loadContracts();
  const readiness = await collectReadiness(contract, ingestionManifest);
  printReadiness(readiness);
}

async function ready() {
  const { contract, ingestionManifest } = await loadContracts();
  const readiness = await collectReadiness(contract, ingestionManifest);
  printReadiness(readiness);
  if (!readiness.every((item) => item.state === "AVAILABLE")) {
    throw new LocalWorkerError(
      "INVALID",
      "local-workers",
      "every operator-hosted worker prerequisite must be available",
    );
  }
}

async function smoke() {
  const { contract, ingestionManifest } = await loadContracts();
  const readiness = await collectReadiness(contract, ingestionManifest);
  printReadiness(readiness);
  if (!readiness.every((item) => item.state === "AVAILABLE")) {
    throw new LocalWorkerError(
      "INVALID",
      "local-workers-smoke",
      "prepare or repair the optional worker profile before smoke execution",
    );
  }
  const state = await readState(contract);
  const fixturePath = absoluteContractPath(contract.ingestion.fixture);
  const fixtureHash = await sha256File(fixturePath);
  const operationId = `localworker-${fixtureHash.slice(0, 16)}`;
  const jobRoot = path.join(generatedRoot, "smoke", `${operationId}-fixture`);
  const inputPath = path.join(jobRoot, "source");
  const outputDirectory = path.join(jobRoot, "output");
  await ensureDirectory(outputDirectory);
  if (!(await regularFileMatches(inputPath, fixtureHash).catch(() => false))) {
    await copyFile(fixturePath, inputPath);
    await chmod(inputPath, 0o400);
  }

  await runCommand(
    "podman",
    ingestionLaunchArguments({
      clamavDirectory: state.clamav.directory,
      components: ingestionManifest.components,
      imageDigest: state.ingestion.imageDigest,
      imageReference: state.ingestion.imageReference,
      inputPath,
      inputSha256: fixtureHash,
      operationId,
      outputDirectory,
      profile: contract.ingestion.profile,
      tessdataDirectory: state.tessdata.directory,
    }),
    { timeout: 120_000 },
  );
  const normalizedPath = path.join(outputDirectory, "normalized-document.json");
  const normalized = await readJson(normalizedPath);
  if (
    normalized.contractVersion !== "normalized-document-v1" ||
    !Array.isArray(normalized.blocks)
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-smoke",
      "worker output did not match normalized-document-v1",
    );
  }

  const audioPath = path.join(jobRoot, "piper.wav");
  await synthesizePiper(state.piper, audioPath);
  const audio = await inspectWav(audioPath);
  const summary = {
    contractVersion: "reflo-local-workers-smoke-v1",
    fixtureSha256: fixtureHash,
    normalizedDocumentSha256: await sha256File(normalizedPath),
    normalizedBlockCount: normalized.blocks.length,
    audioSha256: await sha256File(audioPath),
    audioBytes: audio.byteLength,
    audioSampleRate: audio.sampleRate,
    replaySafePaths: {
      normalizedDocument: normalizedPath,
      audio: audioPath,
    },
    productionEvidence: false,
  };
  console.info(`AVAILABLE local-workers-smoke: ${JSON.stringify(summary)}`);
}

async function cleanup() {
  assertGeneratedRoot();
  const { contract } = await loadContracts();
  if (
    await commandSucceeds("podman", [
      "image",
      "exists",
      contract.ingestion.imageReference,
    ])
  ) {
    const inspect = await inspectImage(contract.ingestion.imageReference);
    if (
      inspect.Config?.Labels?.["org.opencontainers.image.version"] !==
      contract.ingestion.profile
    ) {
      throw new LocalWorkerError(
        "INVALID",
        "cleanup",
        "the local image tag is not a Reflo isolated-ingestion image",
      );
    }
    await runCommand("podman", [
      "image",
      "rm",
      contract.ingestion.imageReference,
    ]);
    console.info(
      `Removed named Reflo image ${contract.ingestion.imageReference}`,
    );
  }
  await rm(generatedRoot, { force: true, recursive: true });
  console.info(`Removed generated worker profile ${generatedRoot}`);
  console.info(
    "Application artifacts, local databases, Podman VM, and the shared ClamAV updater image were preserved",
  );
}

async function collectReadiness(contract, ingestionManifest) {
  let podman;
  try {
    podman = await verifyPodmanHost(contract);
  } catch (error) {
    const item = readinessFromError(error, "podman");
    return [
      item,
      {
        state: "SKIPPED",
        component: "local-workers",
        message:
          "optional profile cannot be evaluated until Podman is supported",
      },
    ];
  }

  if (!(await pathExists(statePath))) {
    return [
      {
        state: "AVAILABLE",
        component: "podman",
        message: podmanReadinessMessage(podman),
      },
      {
        state: (await pathExists(generatedRoot)) ? "INVALID" : "SKIPPED",
        component: "local-workers",
        message: (await pathExists(generatedRoot))
          ? "incomplete profile; run corepack pnpm local-workers:prepare"
          : "optional profile is not prepared; run corepack pnpm local-workers:prepare",
      },
    ];
  }

  let state;
  try {
    state = await readState(contract);
  } catch (error) {
    return [
      {
        state: "AVAILABLE",
        component: "podman",
        message: podmanReadinessMessage(podman),
      },
      readinessFromError(error, "local-workers"),
    ];
  }
  const results = [
    {
      state: "AVAILABLE",
      component: "podman",
      message: podmanReadinessMessage(podman),
    },
  ];
  const checks = [
    [
      "ingestion-worker",
      () => verifyPreparedIngestion(contract, ingestionManifest, state),
    ],
    ["clamav", () => verifyPreparedClamav(contract, state)],
    ["clamav-admission", () => verifyPreparedClamavAdmission(contract, state)],
    ["tessdata", () => verifyPreparedTessdata(contract, state)],
    ["piper", () => verifyPreparedPiper(contract, state)],
    ["local-workers", () => verifyPreparedProfile(state)],
  ];
  for (const [component, check] of checks) {
    try {
      results.push(await check());
    } catch (error) {
      results.push(readinessFromError(error, component));
    }
  }
  return results;
}

function printReadiness(readiness) {
  for (const item of readiness) {
    console.info(`${item.state} ${item.component}: ${item.message}`);
  }
}

function readinessFromError(error, fallbackComponent) {
  if (error instanceof LocalWorkerError) {
    return {
      state: error.state,
      component: error.component,
      message: error.action,
    };
  }
  return {
    state: "INVALID",
    component: fallbackComponent,
    message: "unexpected verification failure; run local-workers:prepare",
  };
}

async function verifyPodmanHost(contract) {
  let versionOutput;
  try {
    versionOutput = (
      await runCommand("podman", ["version", "--format", "json"], {
        timeout: 10_000,
      })
    ).stdout.trim();
  } catch {
    throw new LocalWorkerError(
      "UNSUPPORTED",
      "podman",
      "install development-compatible Podman 5.8.3 or 6.0.1",
    );
  }
  const report = parsePodmanVersionReport(versionOutput);
  if (report === undefined) {
    throw new LocalWorkerError(
      "UNSUPPORTED",
      "podman",
      "could not read both Podman client and server versions",
    );
  }
  if (
    !podmanVersionReportIsSupported(report, contract.supportedPodmanVersions)
  ) {
    throw new LocalWorkerError(
      "UNSUPPORTED",
      "podman",
      `client ${report.clientVersion}, server ${report.serverVersion}; both must match at exactly 5.8.3 or 6.0.1`,
    );
  }
  const rootless = (
    await runPreparationStep(
      "podman",
      "start a supported rootless Podman connection and retry",
      () =>
        runCommand(
          "podman",
          ["info", "--format", "{{.Host.Security.Rootless}}"],
          { timeout: 10_000 },
        ),
    )
  ).stdout.trim();
  if (rootless !== "true") {
    throw new LocalWorkerError(
      "UNSUPPORTED",
      "podman",
      "the local Podman connection must be rootless",
    );
  }
  return report;
}

function podmanReadinessMessage(podman) {
  return `rootless development-compatible Podman client ${podman.clientVersion}, server ${podman.serverVersion}`;
}

async function prepareIngestion(contract, ingestionManifest, podman) {
  const imageReference = contract.ingestion.imageReference;
  const archive = process.env.REFLO_LOCAL_INGESTION_ARCHIVE;
  const archiveSha256 = process.env.REFLO_LOCAL_INGESTION_ARCHIVE_SHA256;
  const archiveConfigured = archive !== undefined && archive.length > 0;
  const archiveSha256Configured =
    archiveSha256 !== undefined && archiveSha256.length > 0;
  if (archiveConfigured !== archiveSha256Configured) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "set REFLO_LOCAL_INGESTION_ARCHIVE and REFLO_LOCAL_INGESTION_ARCHIVE_SHA256 together",
    );
  }
  let archiveLoaded = false;
  if (archiveConfigured) {
    const archivePath = safeAbsoluteInput(
      archive,
      "REFLO_LOCAL_INGESTION_ARCHIVE",
    );
    await verifyRegularFile(archivePath, "ingestion-worker");
    if (!sha256Pattern.test(archiveSha256)) {
      throw new LocalWorkerError(
        "INVALID",
        "ingestion-worker",
        "set REFLO_LOCAL_INGESTION_ARCHIVE_SHA256 for the configured archive",
      );
    }
    await requireDigest(archivePath, archiveSha256, "ingestion-worker");
    console.info(`Loading configured ingestion image archive ${archivePath}`);
    const loaded = await runCommand(
      "podman",
      ["load", "--input", archivePath],
      {
        timeout: 10 * 60_000,
      },
    );
    if (!`${loaded.stdout}\n${loaded.stderr}`.includes(imageReference)) {
      throw new LocalWorkerError(
        "INVALID",
        "ingestion-worker",
        `archive did not load the required ${imageReference} tag`,
      );
    }
    archiveLoaded = true;
  }

  const recordedImageDigest = await readRecordedImageDigest(contract);
  if (
    (archiveLoaded || recordedImageDigest !== undefined) &&
    (await commandSucceeds("podman", ["image", "exists", imageReference]))
  ) {
    try {
      const verified = await verifyImageContract(
        contract,
        ingestionManifest,
        archiveLoaded ? undefined : recordedImageDigest,
      );
      console.info(`Reusing verified ingestion image ${verified.imageDigest}`);
      return {
        ...verified,
        podmanClientVersion: podman.clientVersion,
        podmanServerVersion: podman.serverVersion,
      };
    } catch (error) {
      if (archiveLoaded) throw error;
      console.info("Rebuilding stale or mismatched local ingestion image");
    }
  } else if (
    !(await commandSucceeds("podman", ["image", "exists", imageReference]))
  ) {
    console.info("Building local ingestion image");
  } else {
    console.info(
      "Building the ingestion image because the existing tag has no recorded bootstrap identity",
    );
  }

  if (
    !(await commandSucceeds("git", [
      "diff",
      "--quiet",
      "HEAD",
      "--",
      contract.ingestion.context,
    ]))
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "worker sources are dirty; commit or isolate them before building provenance",
    );
  }
  const sourceRevision = (
    await runCommand("git", [
      "log",
      "-1",
      "--format=%H",
      "--",
      contract.ingestion.context,
    ])
  ).stdout.trim();
  if (!/^[a-f0-9]{40}$/.test(sourceRevision)) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "could not resolve the worker source revision",
    );
  }
  const containerfileRelativePath = path.relative(
    contract.ingestion.context,
    contract.ingestion.containerfile,
  );
  if (
    path.isAbsolute(containerfileRelativePath) ||
    containerfileRelativePath === ".." ||
    containerfileRelativePath.startsWith(`..${path.sep}`)
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "ingestion Containerfile escaped its build context",
    );
  }
  const trackedBuildRoot = await mkdtemp(
    path.join(tmpdir(), "reflo-ingestion-build-"),
  );
  const archivePath = path.join(trackedBuildRoot, "context.tar");
  const buildContext = path.join(trackedBuildRoot, "context");
  await ensureDirectory(buildContext);
  try {
    await runCommand("git", [
      "archive",
      "--format=tar",
      `--output=${archivePath}`,
      `${sourceRevision}:${contract.ingestion.context}`,
    ]);
    await runCommand("tar", [
      "--extract",
      "--file",
      archivePath,
      "--directory",
      buildContext,
    ]);
    await runCommand(
      "podman",
      [
        "build",
        "--platform",
        contract.ingestion.platform,
        "--target",
        "runtime",
        "--build-arg",
        `REFLO_SOURCE_COMMIT=${sourceRevision}`,
        "--tag",
        imageReference,
        "--file",
        path.join(buildContext, containerfileRelativePath),
        buildContext,
      ],
      { maxBuffer: 16 * maximumCommandOutputBytes, timeout: 30 * 60_000 },
    );
  } finally {
    await rm(trackedBuildRoot, { force: true, recursive: true });
  }
  const verified = await verifyImageContract(
    contract,
    ingestionManifest,
    undefined,
  );
  console.info(`Built ingestion image ${verified.imageDigest}`);
  return {
    ...verified,
    podmanClientVersion: podman.clientVersion,
    podmanServerVersion: podman.serverVersion,
  };
}

async function verifyImageContract(
  contract,
  ingestionManifest,
  expectedDigest,
) {
  const imageReference = contract.ingestion.imageReference;
  const inspect = await inspectImage(imageReference);
  const imageDigest = inspect.Digest;
  if (
    !digestPattern.test(imageDigest ?? "") ||
    (expectedDigest !== undefined && imageDigest !== expectedDigest) ||
    `${inspect.Os}/${inspect.Architecture}` !== contract.ingestion.platform ||
    inspect.Config?.User !== "65532:65532" ||
    JSON.stringify(inspect.Config?.Entrypoint) !==
      JSON.stringify(["java", "-jar", "/opt/reflo/worker.jar"]) ||
    inspect.Config?.Labels?.["org.opencontainers.image.version"] !==
      contract.ingestion.profile
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "local image identity, platform, user, entrypoint, or digest is invalid",
    );
  }
  const imageEnvironment = inspect.Config?.Env ?? [];
  if (
    imageEnvironment.some((entry) =>
      /(?:^|_)(?:ACCESS|AUTH|CREDENTIAL|PASSWORD|SECRET|TOKEN)(?:_|=)/i.test(
        entry,
      ),
    )
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "local image contains an ambient credential-shaped environment value",
    );
  }
  const sourceRevision =
    inspect.Config?.Labels?.["org.opencontainers.image.revision"];
  if (
    !/^[a-f0-9]{40}$/.test(sourceRevision ?? "") ||
    !(await commandSucceeds("git", [
      "cat-file",
      "-e",
      `${sourceRevision}^{commit}`,
    ]))
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "image source revision is missing from local Git history",
    );
  }
  if (
    !(await commandSucceeds("git", [
      "diff",
      "--quiet",
      sourceRevision,
      "--",
      contract.ingestion.context,
    ]))
  ) {
    throw new LocalWorkerError(
      "STALE",
      "ingestion-worker",
      "image source no longer matches the checked-in worker; run local-workers:prepare",
    );
  }
  const embeddedManifestOutput = (
    await runCommand(
      "podman",
      [
        "run",
        "--rm",
        "--pull=never",
        "--network=none",
        "--cap-drop=ALL",
        "--security-opt=no-new-privileges",
        "--read-only",
        "--user=65532:65532",
        "--userns=keep-id:uid=65532,gid=65532",
        `--cpus=${ingestionManifest.runtime.cpuCount}`,
        `--memory=${ingestionManifest.runtime.memoryBytes}`,
        `--pids-limit=${ingestionManifest.runtime.pids}`,
        `--tmpfs=/tmp:rw,noexec,nosuid,nodev,size=${ingestionManifest.runtime.temporaryStorageBytes}`,
        "--entrypoint=/bin/cat",
        imageReference,
        "/opt/reflo/worker-manifest.json",
      ],
      { timeout: 30_000 },
    )
  ).stdout;
  let embeddedManifest;
  try {
    embeddedManifest = JSON.parse(embeddedManifestOutput);
  } catch {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "embedded worker manifest is not valid JSON",
    );
  }
  if (JSON.stringify(embeddedManifest) !== JSON.stringify(ingestionManifest)) {
    throw new LocalWorkerError(
      "STALE",
      "ingestion-worker",
      "embedded worker manifest does not match the checked-in contract",
    );
  }
  return {
    imageDigest,
    imageReference,
    sourceRevision,
  };
}

async function verifyPreparedIngestion(contract, ingestionManifest, state) {
  const verified = await verifyImageContract(
    contract,
    ingestionManifest,
    state.ingestion.imageDigest,
  );
  if (
    verified.imageReference !== state.ingestion.imageReference ||
    verified.sourceRevision !== state.ingestion.sourceRevision
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      "recorded image identity does not match the inspected image",
    );
  }
  return {
    state: "AVAILABLE",
    component: "ingestion-worker",
    message: `${verified.imageDigest}; network=none, caps=none, read-only root, user=65532:65532`,
  };
}

async function readRecordedImageDigest(contract) {
  if (!(await pathExists(statePath))) return undefined;
  try {
    const state = await readJson(statePath);
    if (
      state.contractVersion === contract.stateVersion &&
      state.ingestion?.imageReference === contract.ingestion.imageReference &&
      digestPattern.test(state.ingestion?.imageDigest ?? "")
    ) {
      return state.ingestion.imageDigest;
    }
  } catch {
    return undefined;
  }
  return undefined;
}

async function prepareClamav(contract) {
  const image = contract.clamav.updaterImage;
  if (!(await commandSucceeds("podman", ["image", "exists", image]))) {
    console.info("Pulling digest-pinned ClamAV development updater");
    await runCommand(
      "podman",
      ["pull", "--platform", contract.ingestion.platform, image],
      { timeout: 10 * 60_000 },
    );
  }
  await verifyUpdaterImage(contract);

  const targetDirectory = path.join(generatedRoot, "clamav");
  let reuseExistingSnapshot = false;
  if (await pathExists(targetDirectory)) {
    try {
      const existing = await inspectClamavDirectory(contract, targetDirectory);
      console.info(
        `Reusing fresh ClamAV ${contract.clamav.version} snapshot ${existing.dailyBuiltAt}`,
      );
      return {
        ...existing,
        directory: targetDirectory,
        updaterImage: image,
      };
    } catch (error) {
      if (
        error instanceof LocalWorkerError &&
        error.state !== "STALE" &&
        error.state !== "INVALID"
      ) {
        throw error;
      }
      reuseExistingSnapshot =
        error instanceof LocalWorkerError && error.state === "STALE";
      console.info("Refreshing stale or invalid ClamAV development signatures");
    }
  }
  const nextDirectory = path.join(generatedRoot, ".clamav-next");
  const previousDirectory = path.join(generatedRoot, ".clamav-previous");
  await rm(nextDirectory, { force: true, recursive: true });
  await ensureDirectory(nextDirectory);
  if (reuseExistingSnapshot) {
    await cp(targetDirectory, nextDirectory, {
      errorOnExist: false,
      force: true,
      recursive: true,
    });
  } else if (!(await pathExists(targetDirectory))) {
    const legacy = path.join(
      repositoryRoot,
      ".reflo",
      "local-smoke",
      "clamav-database",
    );
    if (await pathExists(legacy)) {
      await cp(legacy, nextDirectory, {
        errorOnExist: false,
        force: true,
        recursive: true,
      });
    }
  }
  await chmod(nextDirectory, 0o700);
  console.info("Refreshing ClamAV development signatures with FreshClam");
  try {
    await runCommand(
      "podman",
      [
        "run",
        "--rm",
        "--pull=never",
        "--cap-drop=ALL",
        "--security-opt=no-new-privileges",
        "--read-only",
        "--user=100:101",
        "--userns=keep-id:uid=100,gid=101",
        "--tmpfs=/tmp:rw,noexec,nosuid,nodev,size=268435456",
        `--mount=type=bind,src=${nextDirectory},dst=/database,rw=true,relabel=private`,
        "--entrypoint=/usr/bin/freshclam",
        image,
        "--stdout",
        "--log=/tmp/freshclam.log",
        "--datadir=/database",
      ],
      { maxBuffer: 4 * maximumCommandOutputBytes, timeout: 10 * 60_000 },
    );
    const snapshot = await inspectClamavDirectory(contract, nextDirectory);
    await rm(previousDirectory, { force: true, recursive: true });
    if (await pathExists(targetDirectory)) {
      await rename(targetDirectory, previousDirectory);
    }
    await rename(nextDirectory, targetDirectory);
    await rm(previousDirectory, { force: true, recursive: true });
    console.info(
      `Verified ClamAV ${contract.clamav.version} snapshot ${snapshot.dailyBuiltAt}`,
    );
    return {
      ...snapshot,
      directory: targetDirectory,
      updaterImage: image,
    };
  } catch (error) {
    await rm(nextDirectory, { force: true, recursive: true });
    if (error instanceof LocalWorkerError) throw error;
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      "FreshClam update failed; verify network access and retry",
    );
  }
}

async function verifyUpdaterImage(contract) {
  const inspect = await inspectImage(contract.clamav.updaterImage);
  if (
    inspect.Digest !== contract.clamav.updaterImageDigest ||
    `${inspect.Os}/${inspect.Architecture}` !== contract.ingestion.platform
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      "ClamAV updater image digest or platform is invalid",
    );
  }
  const version = (
    await runCommand(
      "podman",
      [
        "run",
        "--rm",
        "--pull=never",
        "--network=none",
        "--cap-drop=ALL",
        "--security-opt=no-new-privileges",
        "--read-only",
        "--entrypoint=/usr/bin/freshclam",
        contract.clamav.updaterImage,
        "--version",
      ],
      { timeout: 30_000 },
    )
  ).stdout.trim();
  if (!version.startsWith(`ClamAV ${contract.clamav.version}/`)) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      `updater reported ${version || "an unknown version"}`,
    );
  }
}

async function inspectClamavDirectory(
  contract,
  directory,
  allowedMetadataFiles = contract.clamav.allowedMetadataFiles,
) {
  const sigtoolVersion = (
    await runCommand(
      "podman",
      [
        "run",
        "--rm",
        "--pull=never",
        "--network=none",
        "--cap-drop=ALL",
        "--security-opt=no-new-privileges",
        "--read-only",
        "--entrypoint=/usr/bin/sigtool",
        contract.clamav.updaterImage,
        "--version",
      ],
      { timeout: 30_000 },
    )
  ).stdout.trim();
  if (!sigtoolVersion.startsWith(`ClamAV ${contract.clamav.version}`)) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      `sigtool reported ${sigtoolVersion || "an unknown version"}`,
    );
  }
  const selected = [];
  for (const candidates of contract.clamav.databases) {
    const present = [];
    for (const candidate of candidates) {
      if (await pathExists(path.join(directory, candidate))) {
        present.push(candidate);
      }
    }
    if (present.length !== 1) {
      throw new LocalWorkerError(
        "INVALID",
        "clamav",
        `expected exactly one of ${candidates.join(", ")}`,
      );
    }
    selected.push(present[0]);
  }
  const directoryEntries = await readdir(directory, { withFileTypes: true });
  const unexpectedEntries = unexpectedClamavDirectoryEntries(
    directoryEntries,
    selected,
    allowedMetadataFiles,
  );
  if (unexpectedEntries.length > 0) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      `unexpected database directory entries: ${unexpectedEntries.join(", ")}`,
    );
  }
  const files = [];
  let dailyBuiltAt;
  for (const filename of selected) {
    const filePath = path.join(directory, filename);
    const output = (
      await runCommand(
        "podman",
        [
          "run",
          "--rm",
          "--pull=never",
          "--network=none",
          "--cap-drop=ALL",
          "--security-opt=no-new-privileges",
          "--read-only",
          "--user=100:101",
          "--userns=keep-id:uid=100,gid=101",
          `--mount=type=bind,src=${directory},dst=/database,ro=true,relabel=private`,
          "--entrypoint=/usr/bin/sigtool",
          contract.clamav.updaterImage,
          "--info",
          `/database/${filename}`,
        ],
        { timeout: 120_000 },
      )
    ).stdout;
    if (!output.includes("Verification OK.")) {
      throw new LocalWorkerError(
        "INVALID",
        "clamav",
        `${filename} did not pass upstream signature verification`,
      );
    }
    const buildTimeText = output.match(/^Build time: (.+)$/m)?.[1]?.trim();
    const buildTime = new Date(buildTimeText ?? "");
    const databaseVersion = Number(output.match(/^Version: ([0-9]+)$/m)?.[1]);
    if (!Number.isFinite(buildTime.getTime())) {
      throw new LocalWorkerError(
        "INVALID",
        "clamav",
        `${filename} has no valid signed build time`,
      );
    }
    if (!Number.isSafeInteger(databaseVersion) || databaseVersion < 1) {
      throw new LocalWorkerError(
        "INVALID",
        "clamav",
        `${filename} has no valid database version`,
      );
    }
    if (filename.startsWith("daily.")) {
      dailyBuiltAt = buildTime.toISOString();
    }
    const fileStat = await stat(filePath);
    files.push({
      byteLength: fileStat.size,
      buildTime: buildTime.toISOString(),
      databaseVersion,
      filename,
      sha256: await sha256File(filePath),
    });
  }
  if (dailyBuiltAt === undefined) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      "daily database build time is missing",
    );
  }
  const ageMs = Date.now() - new Date(dailyBuiltAt).getTime();
  if (
    ageMs < -5 * 60_000 ||
    ageMs > contract.clamav.maxAgeHours * 60 * 60_000
  ) {
    throw new LocalWorkerError(
      "STALE",
      "clamav",
      `daily signatures were built at ${dailyBuiltAt}; run local-workers:prepare`,
    );
  }
  files.sort((left, right) => left.filename.localeCompare(right.filename));
  return {
    dailyBuiltAt,
    files,
    toolchain: {
      freshClamImageDigest: contract.clamav.updaterImageDigest,
      sigtoolVersion,
    },
  };
}

async function verifyPreparedClamav(contract, state) {
  if (
    state.clamav.directory !== path.join(generatedRoot, "clamav") ||
    state.clamav.updaterImage !== contract.clamav.updaterImage
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      "recorded ClamAV paths or updater identity are invalid",
    );
  }
  if (
    !(await commandSucceeds("podman", [
      "image",
      "exists",
      contract.clamav.updaterImage,
    ]))
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      "digest-pinned updater image is missing; run local-workers:prepare",
    );
  }
  await verifyUpdaterImage(contract);
  const inspected = await inspectClamavDirectory(
    contract,
    state.clamav.directory,
  );
  if (JSON.stringify(inspected.files) !== JSON.stringify(state.clamav.files)) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav",
      "signature file identities changed after preparation",
    );
  }
  return {
    state: "AVAILABLE",
    component: "clamav",
    message: `ClamAV ${contract.clamav.version} verified snapshot built ${inspected.dailyBuiltAt}`,
  };
}

async function prepareClamavAdmission(contract, clamav) {
  const identity = {
    clamAvVersion: contract.clamav.version,
    contractVersion: clamavManifestContract,
    files: clamav.files.map((file) => ({
      buildTime: file.buildTime,
      byteLength: file.byteLength,
      databaseVersion: file.databaseVersion,
      name: file.filename,
      sha256: file.sha256,
    })),
    profile: clamavAdmissionProfile,
    publishedAt: new Date().toISOString(),
    toolchain: clamav.toolchain,
  };
  const snapshotId = clamavSnapshotId(identity);
  const admissionRoot = path.join(generatedRoot, "clamav-admission");
  const directory = path.join(admissionRoot, snapshotId);
  const manifestPath = path.join(directory, "snapshot.json");
  const manifestBytes = Buffer.from(
    JSON.stringify({ ...identity, snapshotId }),
    "utf8",
  );
  const admission = {
    directory,
    manifestPath,
    manifestSha256: sha256Bytes(manifestBytes),
    profile: clamavAdmissionProfile,
    scannerImage: contract.clamav.updaterImage,
    snapshotId,
  };
  if (await pathExists(directory)) {
    await validateClamavAdmission(contract, clamav, admission);
    return admission;
  }
  await ensureDirectory(admissionRoot);
  const nextDirectory = path.join(admissionRoot, `.${snapshotId}.next`);
  await rm(nextDirectory, { force: true, recursive: true });
  await mkdir(nextDirectory, { mode: 0o700 });
  try {
    for (const file of clamav.files) {
      const source = path.join(clamav.directory, file.filename);
      const destination = path.join(nextDirectory, file.filename);
      await verifyRegularFile(source, "clamav-admission");
      await copyFile(source, destination, fsConstants.COPYFILE_EXCL);
      await chmod(destination, 0o444);
    }
    await writeFile(path.join(nextDirectory, "snapshot.json"), manifestBytes, {
      flag: "wx",
      mode: 0o444,
    });
    await chmod(nextDirectory, 0o555);
    await rename(nextDirectory, directory);
  } catch (error) {
    await chmod(nextDirectory, 0o700).catch(() => undefined);
    await rm(nextDirectory, { force: true, recursive: true });
    throw error;
  }
  await validateClamavAdmission(contract, clamav, admission);
  return admission;
}

async function verifyPreparedClamavAdmission(contract, state) {
  const admission = state.clamavAdmission;
  if (
    admission?.scannerImage !== contract.clamav.updaterImage ||
    admission?.directory === state.clamav.directory ||
    admission?.profile !== clamavAdmissionProfile ||
    path.dirname(admission.directory) !==
      path.join(generatedRoot, "clamav-admission")
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav-admission",
      "recorded upstream snapshot identity is invalid",
    );
  }
  await validateClamavAdmission(contract, state.clamav, admission);
  const inspected = await inspectClamavDirectory(
    contract,
    admission.directory,
    ["snapshot.json"],
  );
  const manifest = await readJson(admission.manifestPath);
  if (
    JSON.stringify(inspected.files) !==
      JSON.stringify(
        manifest.files.map((file) => ({
          byteLength: file.byteLength,
          buildTime: file.buildTime,
          databaseVersion: file.databaseVersion,
          filename: file.name,
          sha256: file.sha256,
        })),
      ) ||
    JSON.stringify(inspected.toolchain) !== JSON.stringify(manifest.toolchain)
  ) {
    throw invalidClamavAdmission();
  }
  return {
    state: "AVAILABLE",
    component: "clamav-admission",
    message: `Upstream-signed immutable snapshot ${admission.snapshotId}`,
  };
}

export async function validateClamavAdmission(
  contract,
  clamav,
  admission,
  now = new Date(),
) {
  if (
    admission.profile !== clamavAdmissionProfile ||
    !/^cvd-[a-f0-9]{32}$/.test(admission.snapshotId ?? "") ||
    !sha256Pattern.test(admission.manifestSha256 ?? "") ||
    path.dirname(admission.manifestPath) !== admission.directory ||
    path.basename(admission.directory) !== admission.snapshotId
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "clamav-admission",
      "content-addressed snapshot paths or identity are invalid",
    );
  }
  await verifyRegularFile(admission.manifestPath, "clamav-admission");
  const manifestBytes = await readFile(admission.manifestPath);
  let manifest;
  try {
    manifest = JSON.parse(manifestBytes.toString("utf8"));
  } catch {
    throw invalidClamavAdmission();
  }
  if (
    !isRecord(manifest) ||
    JSON.stringify(Object.keys(manifest).sort()) !==
      JSON.stringify([
        "clamAvVersion",
        "contractVersion",
        "files",
        "profile",
        "publishedAt",
        "snapshotId",
        "toolchain",
      ]) ||
    manifest.clamAvVersion !== contract.clamav.version ||
    manifest.contractVersion !== clamavManifestContract ||
    manifest.profile !== clamavAdmissionProfile ||
    manifest.snapshotId !== admission.snapshotId ||
    !isRecord(manifest.toolchain) ||
    JSON.stringify(Object.keys(manifest.toolchain).sort()) !==
      JSON.stringify(["freshClamImageDigest", "sigtoolVersion"]) ||
    manifest.toolchain.freshClamImageDigest !==
      contract.clamav.updaterImageDigest ||
    manifest.toolchain.sigtoolVersion !== clamav.toolchain?.sigtoolVersion ||
    !Array.isArray(manifest.files)
  ) {
    throw invalidClamavAdmission();
  }
  const publishedAt = new Date(manifest.publishedAt);
  const daily = manifest.files.find(
    (file) => isRecord(file) && /^daily\.(?:cld|cvd)$/.test(file.name),
  );
  const dailyBuildTime = new Date(
    isRecord(daily) ? daily.buildTime : "",
  ).getTime();
  const publishedAgeMs = now.getTime() - publishedAt.getTime();
  const dailyAgeMs = now.getTime() - dailyBuildTime;
  if (
    !Number.isFinite(now.getTime()) ||
    !Number.isFinite(publishedAt.getTime()) ||
    !Number.isFinite(dailyBuildTime) ||
    publishedAgeMs < -5 * 60_000 ||
    dailyAgeMs < -5 * 60_000 ||
    publishedAgeMs > contract.clamav.maxAgeHours * 60 * 60_000 ||
    dailyAgeMs > contract.clamav.maxAgeHours * 60 * 60_000
  ) {
    throw new LocalWorkerError(
      "STALE",
      "clamav-admission",
      "upstream snapshot is absent or outside the 24-hour admission window",
    );
  }
  const expectedFiles = new Map(
    clamav.files.map((file) => [
      file.filename,
      {
        buildTime: file.buildTime,
        byteLength: file.byteLength,
        databaseVersion: file.databaseVersion,
        sha256: file.sha256,
      },
    ]),
  );
  if (
    manifest.files.length !== expectedFiles.size ||
    manifest.files.some(
      (file) =>
        !isRecord(file) ||
        Object.keys(file).sort().join(",") !==
          "buildTime,byteLength,databaseVersion,name,sha256" ||
        !expectedFiles.has(file.name) ||
        expectedFiles.get(file.name).buildTime !== file.buildTime ||
        expectedFiles.get(file.name).byteLength !== file.byteLength ||
        expectedFiles.get(file.name).databaseVersion !== file.databaseVersion ||
        expectedFiles.get(file.name).sha256 !== file.sha256,
    )
  ) {
    throw invalidClamavAdmission();
  }
  const directoryNames = (await readdir(admission.directory)).sort();
  const allowedNames = [
    ...manifest.files.map((file) => file.name),
    path.basename(admission.manifestPath),
  ].sort();
  if (JSON.stringify(directoryNames) !== JSON.stringify(allowedNames)) {
    throw invalidClamavAdmission();
  }
  for (const file of manifest.files) {
    const filePath = path.join(admission.directory, file.name);
    await verifyRegularFile(filePath, "clamav-admission");
    const fileStat = await stat(filePath);
    if (
      fileStat.size !== file.byteLength ||
      (await sha256File(filePath)) !== file.sha256
    ) {
      throw invalidClamavAdmission();
    }
  }
  if (
    sha256Bytes(manifestBytes) !== admission.manifestSha256 ||
    clamavSnapshotId({
      clamAvVersion: manifest.clamAvVersion,
      contractVersion: manifest.contractVersion,
      files: manifest.files,
      profile: manifest.profile,
      publishedAt: manifest.publishedAt,
      toolchain: manifest.toolchain,
    }) !== admission.snapshotId
  ) {
    throw invalidClamavAdmission();
  }
}

function invalidClamavAdmission() {
  return new LocalWorkerError(
    "INVALID",
    "clamav-admission",
    "upstream signature, manifest, or database identity is invalid",
  );
}

export function clamavSnapshotId(identity) {
  return `cvd-${sha256Bytes(
    Buffer.from(
      JSON.stringify({
        clamAvVersion: identity.clamAvVersion,
        contractVersion: identity.contractVersion,
        files: identity.files,
        profile: identity.profile,
        publishedAt: identity.publishedAt,
        toolchain: identity.toolchain,
      }),
      "utf8",
    ),
  ).slice(0, 32)}`;
}

async function prepareTessdata(contract) {
  const directory = path.join(generatedRoot, "tessdata");
  const filePath = path.join(directory, contract.tessdata.filename);
  await ensureDirectory(directory);
  if (
    !(await regularFileMatches(filePath, contract.tessdata.sha256).catch(
      () => false,
    ))
  ) {
    const legacy = path.join(
      repositoryRoot,
      ".reflo",
      "local-smoke",
      "tessdata",
      contract.tessdata.filename,
    );
    if (
      await regularFileMatches(legacy, contract.tessdata.sha256).catch(
        () => false,
      )
    ) {
      await copyFile(legacy, filePath);
    } else {
      await downloadExact(
        contract.tessdata.url,
        filePath,
        contract.tessdata.sha256,
        "tessdata",
      );
    }
  }
  await chmod(filePath, 0o400);
  return {
    directory,
    filename: contract.tessdata.filename,
    revision: contract.tessdata.revision,
    sha256: await sha256File(filePath),
  };
}

async function verifyPreparedTessdata(contract, state) {
  if (
    state.tessdata.directory !== path.join(generatedRoot, "tessdata") ||
    state.tessdata.filename !== contract.tessdata.filename ||
    state.tessdata.revision !== contract.tessdata.revision ||
    state.tessdata.sha256 !== contract.tessdata.sha256 ||
    !(await regularFileMatches(
      path.join(state.tessdata.directory, state.tessdata.filename),
      contract.tessdata.sha256,
    ).catch(() => false))
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "tessdata",
      "English tessdata identity or checksum is invalid; run local-workers:prepare",
    );
  }
  return {
    state: "AVAILABLE",
    component: "tessdata",
    message: `${state.tessdata.filename} sha256:${state.tessdata.sha256}`,
  };
}

async function preparePiper(contract, runtime) {
  const targetDirectory = path.join(generatedRoot, "piper");
  const nextDirectory = path.join(generatedRoot, ".piper-next");
  const previousDirectory = path.join(generatedRoot, ".piper-previous");
  if (await pathExists(targetDirectory)) {
    try {
      const existingState = await readJson(statePath);
      await verifyPiperDirectory(contract, existingState.piper, runtime);
      console.info("Reusing verified Piper development environment");
      return existingState.piper;
    } catch {
      console.info("Rebuilding stale or mismatched Piper environment");
    }
  }
  await rm(nextDirectory, { force: true, recursive: true });
  await ensureDirectory(nextDirectory);
  const modelPath = path.join(
    nextDirectory,
    path.basename(contract.piper.voice.modelPath),
  );
  const configPath = path.join(
    nextDirectory,
    path.basename(contract.piper.voice.configPath),
  );
  await materializeVoiceArtifact(
    contract,
    "model",
    modelPath,
    contract.piper.voice.modelSha256,
  );
  await materializeVoiceArtifact(
    contract,
    "config",
    configPath,
    contract.piper.voice.configSha256,
  );

  const bootstrapPython = await findBootstrapPython(contract);
  const downloads = path.join(nextDirectory, "downloads");
  await ensureDirectory(downloads);
  console.info(
    `Downloading checksum-pinned Piper ${contract.piper.version} runtime wheels`,
  );
  await runCommand(
    bootstrapPython,
    [
      "-m",
      "pip",
      "download",
      "--disable-pip-version-check",
      "--no-deps",
      "--only-binary=:all:",
      "--dest",
      downloads,
      `piper-tts==${contract.piper.version}`,
      `onnxruntime==${runtime.onnxRuntimeVersion}`,
    ],
    { timeout: 5 * 60_000 },
  );
  const piperWheelPath = path.join(downloads, runtime.piperWheel);
  const onnxWheelPath = path.join(downloads, runtime.onnxRuntimeWheel);
  await requireDigest(piperWheelPath, runtime.piperWheelSha256, "piper");
  await requireDigest(onnxWheelPath, runtime.onnxRuntimeWheelSha256, "piper");

  const venvDirectory = path.join(nextDirectory, "venv");
  await runCommand(bootstrapPython, ["-m", "venv", venvDirectory], {
    timeout: 120_000,
  });
  const pythonExecutable = path.join(venvDirectory, "bin", "python");
  console.info("Installing exact Piper development dependency versions");
  await runCommand(
    pythonExecutable,
    [
      "-m",
      "pip",
      "install",
      "--disable-pip-version-check",
      "--no-cache-dir",
      "--only-binary=:all:",
      ...contract.piper.dependencies,
    ],
    { maxBuffer: 4 * maximumCommandOutputBytes, timeout: 10 * 60_000 },
  );
  await runCommand(
    pythonExecutable,
    [
      "-m",
      "pip",
      "install",
      "--disable-pip-version-check",
      "--no-cache-dir",
      "--no-deps",
      "--no-index",
      "--find-links",
      downloads,
      `piper-tts==${contract.piper.version}`,
      `onnxruntime==${runtime.onnxRuntimeVersion}`,
    ],
    { maxBuffer: 4 * maximumCommandOutputBytes, timeout: 5 * 60_000 },
  );
  const packageIdentity = await inspectPiperPackages(
    pythonExecutable,
    contract,
    runtime,
  );
  const preflightWavPath = path.join(nextDirectory, "preflight.wav");
  const candidate = {
    artifactRevision: contract.piper.voice.revision,
    configPath,
    configSha256: contract.piper.voice.configSha256,
    environmentSha256: packageIdentity.environmentSha256,
    modelPath,
    modelSha256: contract.piper.voice.modelSha256,
    onnxRuntimeVersion: runtime.onnxRuntimeVersion,
    onnxRuntimeWheel: runtime.onnxRuntimeWheel,
    onnxRuntimeWheelSha256: runtime.onnxRuntimeWheelSha256,
    packageFreeze: packageIdentity.packageFreeze,
    piperVersion: contract.piper.version,
    piperWheel: runtime.piperWheel,
    piperWheelSha256: runtime.piperWheelSha256,
    platform: runtime.platform,
    preflightWavPath,
    pythonVersion: packageIdentity.pythonVersion,
    pythonExecutable,
    voiceArtifactVersion: contract.piper.voiceArtifactVersion,
    voiceId: contract.piper.voice.voiceId,
  };
  await synthesizePiper(candidate, preflightWavPath);
  await inspectWav(preflightWavPath);

  await rm(previousDirectory, { force: true, recursive: true });
  if (await pathExists(targetDirectory)) {
    await rename(targetDirectory, previousDirectory);
  }
  await rename(nextDirectory, targetDirectory);
  await rm(previousDirectory, { force: true, recursive: true });
  const final = rebasePiperPaths(candidate, nextDirectory, targetDirectory);
  console.info(`Verified Piper ${final.piperVersion} with ${final.voiceId}`);
  return final;
}

async function materializeVoiceArtifact(
  contract,
  kind,
  destination,
  expectedSha256,
) {
  const legacy = path.join(
    repositoryRoot,
    ".reflo",
    "local-smoke",
    "piper",
    path.basename(destination),
  );
  if (await regularFileMatches(legacy, expectedSha256).catch(() => false)) {
    await copyFile(legacy, destination);
  } else {
    const relativePath =
      kind === "model"
        ? contract.piper.voice.modelPath
        : contract.piper.voice.configPath;
    const url = `https://raw.githubusercontent.com/${contract.piper.voice.repository}/${contract.piper.voice.revision}/${relativePath}`;
    await downloadExact(url, destination, expectedSha256, "piper");
  }
  await chmod(destination, 0o400);
}

async function findBootstrapPython(contract) {
  const configured = process.env.REFLO_LOCAL_PIPER_BOOTSTRAP_PYTHON;
  const executable =
    configured === undefined || configured.length === 0
      ? "python3.13"
      : safeAbsoluteInput(configured, "REFLO_LOCAL_PIPER_BOOTSTRAP_PYTHON");
  let version;
  try {
    version = (
      await runCommand(executable, ["--version"], { timeout: 10_000 })
    ).stdout.trim();
  } catch {
    throw new LocalWorkerError(
      "UNSUPPORTED",
      "piper",
      `install Python ${contract.piper.pythonVersion} or set REFLO_LOCAL_PIPER_BOOTSTRAP_PYTHON`,
    );
  }
  if (version !== `Python ${contract.piper.pythonVersion}`) {
    throw new LocalWorkerError(
      "UNSUPPORTED",
      "piper",
      `${version}; expected exactly Python ${contract.piper.pythonVersion}`,
    );
  }
  return executable;
}

async function inspectPiperPackages(pythonExecutable, contract, runtime) {
  const pythonVersion = (
    await runCommand(pythonExecutable, ["--version"], { timeout: 10_000 })
  ).stdout.trim();
  if (pythonVersion !== `Python ${contract.piper.pythonVersion}`) {
    throw new LocalWorkerError(
      "INVALID",
      "piper",
      `${pythonVersion}; expected exactly Python ${contract.piper.pythonVersion}`,
    );
  }
  const output = (
    await runCommand(
      pythonExecutable,
      [
        "-c",
        [
          "import importlib.metadata as m",
          "import json",
          "names=['piper-tts','onnxruntime']",
          "print(json.dumps({name:m.version(name) for name in names},sort_keys=True))",
        ].join(";"),
      ],
      { timeout: 30_000 },
    )
  ).stdout.trim();
  let versions;
  try {
    versions = JSON.parse(output);
  } catch {
    throw new LocalWorkerError(
      "INVALID",
      "piper",
      "could not inspect the Piper Python environment",
    );
  }
  if (
    versions["piper-tts"] !== contract.piper.version ||
    versions.onnxruntime !== runtime.onnxRuntimeVersion
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "piper",
      "installed Piper or ONNX Runtime version is not pinned",
    );
  }
  const packageFreeze = (
    await runCommand(pythonExecutable, ["-m", "pip", "freeze", "--all"], {
      timeout: 30_000,
    })
  ).stdout
    .trim()
    .split("\n")
    .filter((line) => line.length > 0)
    .sort();
  for (const dependency of contract.piper.dependencies) {
    if (!packageFreeze.includes(dependency)) {
      throw new LocalWorkerError(
        "INVALID",
        "piper",
        `installed environment is missing ${dependency}`,
      );
    }
  }
  const identity = [
    `python=${contract.piper.pythonVersion}`,
    `piper=${runtime.piperWheelSha256}`,
    `onnxruntime=${runtime.onnxRuntimeWheelSha256}`,
    ...packageFreeze,
  ].join("\n");
  return {
    environmentSha256: sha256Bytes(Buffer.from(identity, "utf8")),
    packageFreeze,
    pythonVersion: contract.piper.pythonVersion,
  };
}

async function verifyPiperDirectory(contract, state, runtime) {
  const piperDirectory = path.join(generatedRoot, "piper");
  if (
    state === undefined ||
    !piperStatePathsMatch(state, piperDirectory, contract.piper.voice) ||
    state.platform !== runtime.platform ||
    state.pythonVersion !== contract.piper.pythonVersion ||
    state.piperVersion !== contract.piper.version ||
    state.piperWheel !== runtime.piperWheel ||
    state.piperWheelSha256 !== runtime.piperWheelSha256 ||
    state.onnxRuntimeVersion !== runtime.onnxRuntimeVersion ||
    state.onnxRuntimeWheel !== runtime.onnxRuntimeWheel ||
    state.onnxRuntimeWheelSha256 !== runtime.onnxRuntimeWheelSha256 ||
    state.voiceArtifactVersion !== contract.piper.voiceArtifactVersion ||
    state.artifactRevision !== contract.piper.voice.revision ||
    state.modelSha256 !== contract.piper.voice.modelSha256 ||
    state.configSha256 !== contract.piper.voice.configSha256
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "piper",
      "recorded Piper identities do not match the checked-in contract",
    );
  }
  await Promise.all([
    requireDigest(state.modelPath, state.modelSha256, "piper"),
    requireDigest(state.configPath, state.configSha256, "piper"),
    requireDigest(
      path.join(
        path.dirname(path.dirname(path.dirname(state.pythonExecutable))),
        "downloads",
        state.piperWheel,
      ),
      state.piperWheelSha256,
      "piper",
    ),
    requireDigest(
      path.join(
        path.dirname(path.dirname(path.dirname(state.pythonExecutable))),
        "downloads",
        state.onnxRuntimeWheel,
      ),
      state.onnxRuntimeWheelSha256,
      "piper",
    ),
  ]);
  const inspected = await inspectPiperPackages(
    state.pythonExecutable,
    contract,
    runtime,
  );
  if (
    inspected.environmentSha256 !== state.environmentSha256 ||
    JSON.stringify(inspected.packageFreeze) !==
      JSON.stringify(state.packageFreeze)
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "piper",
      "Piper Python environment changed after preparation",
    );
  }
  await inspectWav(state.preflightWavPath);
}

async function verifyPreparedPiper(contract, state) {
  const runtime = selectPiperRuntime(contract);
  await verifyPiperDirectory(contract, state.piper, runtime);
  return {
    state: "AVAILABLE",
    component: "piper",
    message: `development-only piper-tts ${state.piper.piperVersion}, ${state.piper.voiceId}, environment sha256:${state.piper.environmentSha256}`,
  };
}

async function verifyPreparedProfile(state) {
  const expected = renderProfileEnvironment(state);
  let actual;
  try {
    actual = await readFile(profileEnvironmentPath, "utf8");
  } catch {
    throw new LocalWorkerError(
      "INVALID",
      "local-workers",
      "generated profile.env is missing; run local-workers:prepare",
    );
  }
  const profileStat = await stat(profileEnvironmentPath);
  if (actual !== expected || (profileStat.mode & 0o777) !== 0o600) {
    throw new LocalWorkerError(
      "INVALID",
      "local-workers",
      "profile.env content or permissions changed; run local-workers:prepare",
    );
  }
  return {
    state: "AVAILABLE",
    component: "local-workers",
    message:
      "optional upload/audio profile is ready; development smoke is not production activation evidence",
  };
}

function selectPiperRuntime(contract) {
  const key = hostPlatformKey();
  const runtime = contract.piper.runtimes.find(
    (candidate) => candidate.platform === key,
  );
  if (runtime === undefined) {
    throw new LocalWorkerError(
      "UNSUPPORTED",
      "piper",
      `host platform ${key} has no checksum-pinned Piper runtime`,
    );
  }
  return runtime;
}

function rebasePiperPaths(state, from, to) {
  const rebase = (value) =>
    value === from
      ? to
      : value.startsWith(from + path.sep)
        ? to + value.slice(from.length)
        : value;
  return {
    ...state,
    configPath: rebase(state.configPath),
    modelPath: rebase(state.modelPath),
    preflightWavPath: rebase(state.preflightWavPath),
    pythonExecutable: rebase(state.pythonExecutable),
  };
}

async function synthesizePiper(piper, outputPath) {
  await ensureDirectory(path.dirname(outputPath));
  await runWithInput(
    piper.pythonExecutable,
    [
      audioWorkerPath,
      "--config",
      piper.configPath,
      "--config-sha256",
      piper.configSha256,
      "--model",
      piper.modelPath,
      "--model-sha256",
      piper.modelSha256,
      "--output",
      outputPath,
      "--speaking-rate",
      "1",
    ],
    JSON.stringify({
      narration:
        "Reflo development audio verifies the pinned local Piper worker.",
    }),
    {
      CUDA_VISIBLE_DEVICES: "",
      PYTHONDONTWRITEBYTECODE: "1",
      PYTHONNOUSERSITE: "1",
    },
    120_000,
  );
}

async function inspectWav(filePath) {
  const bytes = await readFile(filePath);
  if (
    bytes.byteLength < 44 ||
    bytes.subarray(0, 4).toString("ascii") !== "RIFF" ||
    bytes.subarray(8, 12).toString("ascii") !== "WAVE"
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "piper",
      "Piper output is not a playable WAV file",
    );
  }
  const sampleRate = bytes.readUInt32LE(24);
  if (sampleRate !== 22_050 && sampleRate !== 24_000) {
    throw new LocalWorkerError(
      "INVALID",
      "piper",
      `Piper WAV sample rate ${sampleRate} is unsupported`,
    );
  }
  return { byteLength: bytes.byteLength, sampleRate };
}

export function ingestionLaunchArguments(input) {
  return [
    "run",
    "--rm",
    "--pull=never",
    "--network=none",
    "--cap-drop=ALL",
    "--security-opt=no-new-privileges",
    "--read-only",
    "--user=65532:65532",
    "--userns=keep-id:uid=65532,gid=65532",
    "--cpus=2",
    "--memory=4294967296",
    "--pids-limit=256",
    "--tmpfs=/tmp:rw,noexec,nosuid,nodev,size=4294967296",
    `--mount=type=bind,src=${input.inputPath},dst=/work/input/source,ro=true,relabel=private`,
    `--mount=type=bind,src=${input.outputDirectory},dst=/work/output,rw=true,relabel=private`,
    `--mount=type=bind,src=${input.clamavDirectory},dst=/opt/clamav/database,ro=true,relabel=private`,
    `--mount=type=bind,src=${input.tessdataDirectory},dst=/opt/tessdata,ro=true,relabel=private`,
    `--env=REFLO_INGESTION_PROFILE=${input.profile}`,
    "--env=REFLO_DOCUMENT_KIND=pdf",
    `--env=REFLO_INPUT_SHA256=${input.inputSha256}`,
    `--env=REFLO_OPERATION_ID=${input.operationId}`,
    "--env=REFLO_PROCESSING_LANE=standard",
    `--env=REFLO_WORKER_IMAGE_DIGEST=${input.imageDigest}`,
    `--env=REFLO_CLAMAV_VERSION=${input.components.scanner.replace("clamav-", "")}`,
    `--env=REFLO_OCR_LANGUAGE_PROFILE=${input.components.ocrLanguage}`,
    `--env=REFLO_TESSERACT_VERSION=${input.components.ocrEngine}`,
    `--env=REFLO_TIKA_VERSION=${input.components.parser}`,
    input.imageReference,
  ];
}

async function readState(contract) {
  let state;
  try {
    state = await readJson(statePath);
  } catch {
    throw new LocalWorkerError(
      "INVALID",
      "local-workers",
      "state.json is missing or malformed; run local-workers:prepare",
    );
  }
  if (
    state.contractVersion !== contract.stateVersion ||
    state.profile !== contract.profile ||
    state.hostPlatform !== hostPlatformKey() ||
    typeof state.preparedAt !== "string" ||
    typeof state.ingestion !== "object" ||
    typeof state.clamav !== "object" ||
    typeof state.clamavAdmission !== "object" ||
    typeof state.tessdata !== "object" ||
    typeof state.piper !== "object"
  ) {
    throw new LocalWorkerError(
      state.hostPlatform === hostPlatformKey() ? "INVALID" : "UNSUPPORTED",
      "local-workers",
      "state identity or host platform is invalid; run local-workers:prepare",
    );
  }
  return state;
}

async function inspectImage(reference) {
  let parsed;
  try {
    parsed = JSON.parse(
      (
        await runCommand("podman", ["image", "inspect", reference], {
          timeout: 20_000,
        })
      ).stdout,
    );
  } catch {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      `cannot inspect ${reference}; run local-workers:prepare`,
    );
  }
  if (!Array.isArray(parsed) || parsed.length !== 1) {
    throw new LocalWorkerError(
      "INVALID",
      "ingestion-worker",
      `unexpected image inspection result for ${reference}`,
    );
  }
  return parsed[0];
}

async function downloadExact(url, destination, expectedSha256, component) {
  const temporary = `${destination}.download`;
  await rm(temporary, { force: true });
  try {
    await runCommand(
      "curl",
      [
        "--fail",
        "--location",
        "--proto",
        "=https",
        "--tlsv1.2",
        "--silent",
        "--show-error",
        "--max-time",
        "600",
        "--output",
        temporary,
        url,
      ],
      { timeout: 11 * 60_000 },
    );
    await requireDigest(temporary, expectedSha256, component);
    await rename(temporary, destination);
  } catch (error) {
    await rm(temporary, { force: true });
    if (error instanceof LocalWorkerError) throw error;
    throw new LocalWorkerError(
      "INVALID",
      component,
      `failed to download checksum-pinned artifact ${path.basename(destination)}`,
    );
  }
}

async function requireDigest(filePath, expectedSha256, component) {
  await verifyRegularFile(filePath, component);
  const actual = await sha256File(filePath);
  if (actual !== expectedSha256) {
    throw new LocalWorkerError(
      "INVALID",
      component,
      `${path.basename(filePath)} checksum ${actual} does not match the checked-in identity`,
    );
  }
}

async function regularFileMatches(filePath, expectedSha256) {
  await verifyRegularFile(filePath, "artifact");
  return (await sha256File(filePath)) === expectedSha256;
}

async function verifyRegularFile(filePath, component) {
  try {
    await access(filePath, fsConstants.R_OK);
    if (!(await stat(filePath)).isFile()) throw new Error("not a file");
  } catch {
    throw new LocalWorkerError(
      "INVALID",
      component,
      `required file is missing: ${filePath}`,
    );
  }
}

async function sha256File(filePath) {
  return sha256Bytes(await readFile(filePath));
}

function sha256Bytes(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, "utf8"));
}

async function writePrivateJson(filePath, value) {
  await writePrivateFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

async function writePrivateFile(filePath, value) {
  await ensureDirectory(path.dirname(filePath));
  const temporary = `${filePath}.next`;
  await writeFile(temporary, value, { encoding: "utf8", mode: 0o600 });
  await chmod(temporary, 0o600);
  await rename(temporary, filePath);
  await chmod(filePath, 0o600);
}

async function ensureDirectory(directory) {
  await mkdir(directory, { mode: 0o700, recursive: true });
}

async function pathExists(target) {
  try {
    await access(target);
    return true;
  } catch {
    return false;
  }
}

function absoluteContractPath(relative) {
  if (
    typeof relative !== "string" ||
    path.isAbsolute(relative) ||
    relative.includes("..")
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "contract",
      `unsafe repository path ${String(relative)}`,
    );
  }
  const resolved = path.resolve(repositoryRoot, relative);
  if (!resolved.startsWith(repositoryRoot + path.sep)) {
    throw new LocalWorkerError(
      "INVALID",
      "contract",
      `repository path escaped the root: ${relative}`,
    );
  }
  return resolved;
}

function safeAbsoluteInput(value, name) {
  if (
    !path.isAbsolute(value) ||
    value.includes("\n") ||
    value.includes("\r") ||
    value === path.parse(value).root
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "configuration",
      `${name} must be a safe absolute path`,
    );
  }
  return path.resolve(value);
}

function requiredEnvironment(name) {
  const value = process.env[name]?.trim();
  if (value === undefined || value === "") {
    throw new LocalWorkerError(
      "INVALID",
      "configuration",
      `${name} is required`,
    );
  }
  return value;
}

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function assertGeneratedRoot() {
  const expectedParent = path.join(repositoryRoot, ".reflo");
  if (
    path.dirname(generatedRoot) !== expectedParent ||
    path.basename(generatedRoot) !== "local-workers"
  ) {
    throw new LocalWorkerError(
      "INVALID",
      "cleanup",
      "generated worker root is not safely scoped",
    );
  }
}

function shellQuote(value) {
  if (typeof value !== "string" || /[\r\n\0]/.test(value)) {
    throw new LocalWorkerError(
      "INVALID",
      "profile",
      "environment value is not safe to serialize",
    );
  }
  return `'${value.replaceAll("'", "'\"'\"'")}'`;
}

async function commandSucceeds(executable, args) {
  try {
    await runCommand(executable, args, { timeout: 20_000 });
    return true;
  } catch {
    return false;
  }
}

async function runPreparationStep(component, action, operation) {
  try {
    return await operation();
  } catch (error) {
    if (error instanceof LocalWorkerError) throw error;
    throw new LocalWorkerError("INVALID", component, action);
  }
}

async function runCommand(executable, args, options = {}) {
  try {
    const result = await execFileAsync(executable, args, {
      encoding: "utf8",
      env: options.env ?? process.env,
      maxBuffer: options.maxBuffer ?? maximumCommandOutputBytes,
      timeout: options.timeout ?? 60_000,
    });
    return {
      stderr: result.stderr ?? "",
      stdout: result.stdout ?? "",
    };
  } catch {
    throw new Error(`command failed: ${path.basename(executable)}`);
  }
}

function runWithInput(executable, args, input, environment, timeoutMs) {
  return new Promise((resolve, reject) => {
    const child = spawn(executable, args, {
      env: environment,
      shell: false,
      stdio: ["pipe", "pipe", "pipe"],
    });
    let outputBytes = 0;
    const timer = setTimeout(() => child.kill("SIGKILL"), timeoutMs);
    const count = (chunk) => {
      outputBytes += chunk.byteLength;
      if (outputBytes > maximumCommandOutputBytes) child.kill("SIGKILL");
    };
    child.stdout.on("data", count);
    child.stderr.on("data", count);
    child.on("error", () => {
      clearTimeout(timer);
      reject(new Error("Piper process failed to launch"));
    });
    child.on("close", (code, signal) => {
      clearTimeout(timer);
      if (code === 0 && signal === null) {
        resolve();
      } else {
        reject(new Error("Piper process failed"));
      }
    });
    child.stdin.end(input);
  });
}

function usage() {
  console.info(`Usage: node scripts/local-workers.mjs <command>

Commands:
  prepare  Build/load and verify the optional ingestion and Piper profile.
  status   Report AVAILABLE, SKIPPED, STALE, UNSUPPORTED, or INVALID states.
  ready    Require every operator-hosted worker prerequisite to be AVAILABLE.
  smoke    Run the committed fixture through ingestion and produce a WAV.
  cleanup  Remove only the named Reflo image and generated worker profile.`);
}

async function main() {
  const command = process.argv[2];
  switch (command) {
    case "prepare":
      await prepare();
      return;
    case "status":
      await status();
      return;
    case "ready":
      await ready();
      return;
    case "smoke":
      await smoke();
      return;
    case "cleanup":
      await cleanup();
      return;
    case "help":
    case "--help":
    case "-h":
      usage();
      return;
    default:
      usage();
      process.exitCode = 2;
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    if (error instanceof LocalWorkerError) {
      console.error(`${error.state} ${error.component}: ${error.action}`);
    } else {
      console.error("INVALID local-workers: unexpected failure");
    }
    process.exitCode = 1;
  });
}
